### ISSUE TITLE
Incorporate cyclone mortality into ADRIAmod

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#516]
The idea is to adapt a R script sent from Vanessa Haller (C~Scape).

- [x] [Develop cyclone mortality models based on R implementation #529](https://github.com/open-AIMS/ADRIA.jl/issues/529) [ @Zapiano ]
- [x] [Filter coral species/site by branching_below_5, branching_above_5 and massive #530](https://github.com/open-AIMS/ADRIA.jl/issues/530) [ @Zapiano or @Rosejoycrocker ]
- [x] [Use cyclone mortality model and filter to implement cyclone mortality in ADRIAmod #531](https://github.com/open-AIMS/ADRIA.jl/issues/531) [ @Rosejoycrocker ]
- [x] [Add documentation for Cyclones mortality #544](https://github.com/open-AIMS/ADRIA.jl/issues/544) [ @Zapiano ]

**Comment by Zapiano** [comment]
Me and @Rosejoycrocker agreed to merge everything to the branch `cyclone-mortality` and then merge `cyclone-mortality` into the main branch.

**Comment by ConnectedSystems** [comment]
@Zapiano I believe this issue can be closed?

**Comment by Zapiano** [comment]
> [@Zapiano](https://github.com/Zapiano) I believe this issue can be closed?

Issue #544 needs to be closed first, and now there's a PR #936 to address that.
